In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("sales_train_evaluation.csv")

In [4]:
df.head(5)

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1932,d_1933,d_1934,d_1935,d_1936,d_1937,d_1938,d_1939,d_1940,d_1941
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,4,0,0,0,0,3,3,0,1
1,HOBBIES_1_002_CA_1_evaluation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,1,2,1,1,0,0,0,0,0
2,HOBBIES_1_003_CA_1_evaluation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,0,2,0,0,0,2,3,0,1
3,HOBBIES_1_004_CA_1_evaluation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,1,0,4,0,1,3,0,2,6
4,HOBBIES_1_005_CA_1_evaluation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,0,0,2,1,0,0,2,1,0

In [5]:
df.shape

(30490, 1947)

In [6]:
# Time range d1 to d1941 = 1941 days

In [7]:
# Unique SKUs/store
df.groupby("store_id")["item_id"].nunique()

store_id
CA_1    3049
CA_2    3049
CA_3    3049
CA_4    3049
TX_1    3049
TX_2    3049
TX_3    3049
WI_1    3049
WI_2    3049
WI_3    3049
Name: item_id, dtype: int64

In [8]:
df.loc[:, "d_1":].isnull().sum().any()

np.False_

In [9]:
# The data is daily not weekly

In [10]:
cal = pd.read_csv("calendar.csv")

In [11]:
cal.head(5)

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,NaN,NaN,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,NaN,NaN,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,NaN,NaN,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,NaN,NaN,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,NaN,NaN,1,0,1

In [12]:
cal.shape

(1969, 14)

In [13]:
# Pivoting rows to columns using melt() to have demand of 1941 days in column wise.

id_cols = ["id", "item_id", "dept_id", "cat_id", "store_id", "state_id"]

df_long = df.melt(id_vars = id_cols, var_name = "d", value_name = "demand") 
df_long.shape

(59181090, 8)

In [14]:
df_long.head(5)

,id,item_id,dept_id,cat_id,store_id,state_id,d,demand
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
1,HOBBIES_1_002_CA_1_evaluation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
2,HOBBIES_1_003_CA_1_evaluation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
3,HOBBIES_1_004_CA_1_evaluation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
4,HOBBIES_1_005_CA_1_evaluation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0

In [15]:
df_merged = df_long.merge(cal[["d", "date", "wm_yr_wk", "event_name_1", "event_type_1", "event_name_2", "event_type_2"]], on = 'd', how = 'left')
df_merged.head(5)

,id,item_id,dept_id,cat_id,store_id,state_id,d,demand,date,wm_yr_wk,event_name_1,event_type_1,event_name_2,event_type_2
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,NaN,NaN,NaN,NaN
1,HOBBIES_1_002_CA_1_evaluation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,NaN,NaN,NaN,NaN
2,HOBBIES_1_003_CA_1_evaluation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,NaN,NaN,NaN,NaN
3,HOBBIES_1_004_CA_1_evaluation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,NaN,NaN,NaN,NaN
4,HOBBIES_1_005_CA_1_evaluation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,NaN,NaN,NaN,NaN

In [16]:
df_merged.shape

(59181090, 14)

In [17]:
sell_prices = pd.read_csv("sell_prices.csv")
sell_prices.head(5)

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26
3     CA_1  HOBBIES_1_001     11328        8.26
4     CA_1  HOBBIES_1_001     11329        8.26

In [18]:
sell_prices.shape

(6841121, 4)

In [19]:
sell_prices.isnull().sum()

store_id      0
item_id       0
wm_yr_wk      0
sell_price    0
dtype: int64

In [20]:
# Checking the total demand and zero-demand % per store
store_summary = df_merged.groupby(['state_id','store_id']).agg(
    total_demand    = ('demand', 'sum'),
    zero_demand_pct = ('demand', lambda x: (x == 0).mean() * 100)
).reset_index().sort_values(['state_id', 'total_demand'], ascending=[True, False])

print(store_summary)

  state_id store_id  total_demand  zero_demand_pct
2       CA     CA_3      11363540        59.399768
0       CA     CA_1       7832248        63.759049
1       CA     CA_2       5818395        68.810291
3       CA     CA_4       4182534        71.999519
5       TX     TX_2       7329642        66.314172
6       TX     TX_3       6205940        69.715073
4       TX     TX_1       5692823        70.714074
8       WI     WI_2       6697988        70.480047
9       WI     WI_3       6542557        70.031610
7       WI     WI_1       5261506        68.754056

In [21]:
# Creating a subset of df_merged with just the top stores from each state "stores_to_keep" for ML training.

stores_to_keep = ['CA_3', 'TX_2', 'WI_3']
df = df_merged[df_merged['store_id'].isin(stores_to_keep)].copy()

print(df.shape)
print(df['store_id'].value_counts())

(17754327, 14)
store_id
CA_3    5918109
TX_2    5918109
WI_3    5918109
Name: count, dtype: int64

In [22]:
# Converting 'date' col to datetime data type 

df['date'] = pd.to_datetime(df['date'])

In [23]:
df.head(5)

,id,item_id,dept_id,cat_id,store_id,state_id,d,demand,date,wm_yr_wk,event_name_1,event_type_1,event_name_2,event_type_2
6098,HOBBIES_1_001_CA_3_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_3,CA,d_1,0,2011-01-29,11101,NaN,NaN,NaN,NaN
6099,HOBBIES_1_002_CA_3_evaluation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_3,CA,d_1,0,2011-01-29,11101,NaN,NaN,NaN,NaN
6100,HOBBIES_1_003_CA_3_evaluation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_3,CA,d_1,0,2011-01-29,11101,NaN,NaN,NaN,NaN
6101,HOBBIES_1_004_CA_3_evaluation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_3,CA,d_1,0,2011-01-29,11101,NaN,NaN,NaN,NaN
6102,HOBBIES_1_005_CA_3_evaluation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_3,CA,d_1,0,2011-01-29,11101,NaN,NaN,NaN,NaN

In [34]:
df['has_sporting_event']  = ((df['event_type_1'] == 'Sporting')  | (df['event_type_2'] == 'Sporting')).astype(int)
df['has_national_event']  = ((df['event_type_1'] == 'National')  | (df['event_type_2'] == 'National')).astype(int)
df['has_religious_event'] = ((df['event_type_1'] == 'Religious') | (df['event_type_2'] == 'Religious')).astype(int)
df['has_cultural_event']  = ((df['event_type_1'] == 'Cultural')  | (df['event_type_2'] == 'Cultural')).astype(int)
df['event_count']         = (df['event_name_1'].notna().astype(int) + df['event_name_2'].notna().astype(int))

In [35]:
df_weekly = df.groupby(
    ['item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'wm_yr_wk'],
    as_index=False
).agg(
    weekly_demand        = ('demand', 'sum'),
    date                 = ('date', 'first'),
    sporting_event_days   = ('has_sporting_event', 'sum'),
    national_event_days  = ('has_national_event', 'sum'),
    religious_event_days  = ('has_religious_event','sum'),
    cultural_event_days   = ('has_cultural_event', 'sum'),
    weekly_event_count   = ('event_count', 'sum'),
)

df_weekly = df_weekly.sort_values(
    ['item_id', 'store_id', 'wm_yr_wk']
).reset_index(drop=True)

In [36]:
df_weekly.head(5)
print(df_weekly.shape)

(2542866, 13)

In [37]:
df_weekly = df_weekly.merge(
    sell_prices[['store_id', 'item_id', 'wm_yr_wk', 'sell_price']],
    on=['store_id', 'item_id', 'wm_yr_wk'],
    how='left'
)

In [38]:
# After merging with sell_prices data

df_weekly.head(5)

,item_id,dept_id,cat_id,store_id,state_id,wm_yr_wk,weekly_demand,date,sporting_event_days,national_event_days,religious_event_days,cultural_event_days,weekly_event_count,sell_price
0,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11101,8,2011-01-29,0,0,0,0,0,2.0
1,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11102,9,2011-02-05,1,0,0,0,1,2.0
2,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11103,17,2011-02-12,0,0,0,1,1,2.0
3,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11104,6,2011-02-19,0,1,0,0,1,2.0
4,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11105,18,2011-02-26,0,0,0,0,0,2.0

In [39]:
print(df_weekly.shape)
print(df_weekly['sell_price'].isnull().sum())

(2542866, 14)
488156

In [40]:
weeks_per_sku = df_weekly.groupby(['item_id', 'store_id'])['wm_yr_wk'].count()
print(weeks_per_sku.describe())

sample = df_weekly[
    (df_weekly['item_id'] == 'HOBBIES_1_001') &
    (df_weekly['store_id'] == 'CA_3')
]
print(f"Total weeks for this item-store: {len(sample)}")
#print(sample.head(10))

count    9147.0
mean      278.0
std         0.0
min       278.0
25%       278.0
50%       278.0
75%       278.0
max       278.0
Name: wm_yr_wk, dtype: float64
Total weeks for this item-store: 278

In [44]:
# Which categories have the most missing prices?
null_prices = df_weekly[df_weekly['sell_price'].isnull()]
print(null_prices.groupby('cat_id')['sell_price'].count())
print(null_prices.groupby('cat_id').size())

cat_id
FOODS        0
HOBBIES      0
HOUSEHOLD    0
Name: sell_price, dtype: int64
cat_id
FOODS        225805
HOBBIES       89895
HOUSEHOLD    172456
dtype: int64

In [45]:
# Are nulls concentrated at the start or end of the time period?
print(null_prices['wm_yr_wk'].describe())

count    488156.000000
mean      11208.525207
std          92.386608
min       11101.000000
25%       11127.000000
50%       11207.000000
75%       11250.000000
max       11602.000000
Name: wm_yr_wk, dtype: float64

In [46]:
# Sort first to ensure correct order before filling
df_weekly = df_weekly.sort_values(['item_id', 'store_id', 'wm_yr_wk'])

# Backfill first (fills early nulls with first known price)
# Then forward fill (handles any remaining mid-series gaps)
df_weekly['sell_price'] = df_weekly.groupby(
    ['item_id', 'store_id']
)['sell_price'].transform(lambda x: x.bfill().ffill())

# Verify nulls are gone
print(df_weekly['sell_price'].isnull().sum())

0

## Simulating Lead Times ##
### Since actual supplier lead time data is not available in the dataset ###

In [53]:
import numpy as np

def simulate_lead_time(df, seed=42):
    rng = np.random.default_rng(seed)
    
    profiles = {
        'FOODS':     {'mean': 3,  'std': 1.0},
        'HOUSEHOLD': {'mean': 7,  'std': 2.0},
        'HOBBIES':   {'mean': 10, 'std': 3.0},
    }
    
    lead_times = np.zeros(len(df))
    
    for cat, params in profiles.items():
        mask = df['cat_id'] == cat
        count = mask.sum()
        lt = rng.normal(loc=params['mean'], scale=params['std'], size=count)
        lt = np.clip(lt, 1, None)
        lead_times[mask] = lt
    
    return lead_times

df_weekly['lead_time_days']  = simulate_lead_time(df_weekly)
df_weekly['lead_time_weeks'] = df_weekly['lead_time_days'] / 7

In [56]:
# Checking for zeros or negatives
print(df_weekly['lead_time_days'].min())
print(df_weekly['lead_time_weeks'].min())

# Checking if the distributions look realistic per category
print(df_weekly.groupby('cat_id')[['lead_time_days']].agg(['mean','std']))

1.0
0.14285714285714285
          lead_time_days
                    mean       std
cat_id
FOODS           3.008885  0.979889
HOBBIES        10.002474  2.998192
HOUSEHOLD       7.002475  1.996377

In [58]:
df_weekly.head(3)

,item_id,dept_id,cat_id,store_id,state_id,wm_yr_wk,weekly_demand,date,sporting_event_days,national_event_days,religious_event_days,cultural_event_days,weekly_event_count,sell_price,lead_time_days,lead_time_weeks
0,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11101,8,2011-01-29,0,0,0,0,0,2.0,3.304717,0.472102
1,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11102,9,2011-02-05,1,0,0,0,1,2.0,1.960016,0.280002
2,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11103,17,2011-02-12,0,0,0,1,1,2.0,3.750451,0.535779

#### Rolling Statistics for "Demand" ####

In [112]:
# Feature Engineering. Generating Rolling demand stats for 4/8/13 weeks.

for w in [4, 8, 13]:
    df_weekly[f'demand_mean_{w}w'] = df_weekly.groupby(
        ['item_id', 'store_id'])['weekly_demand'].transform(
        lambda x: x.shift(1).rolling(w, min_periods=w).mean())
    
    df_weekly[f'demand_std_{w}w'] = df_weekly.groupby(
        ['item_id', 'store_id'])['weekly_demand'].transform(
        lambda x: x.shift(1).rolling(w, min_periods=w).std())
    
    df_weekly[f'demand_cv_{w}w'] = (
        df_weekly[f'demand_std_{w}w'] / 
        (df_weekly[f'demand_mean_{w}w'] + 1e-9)
    )

In [61]:
df_weekly.head(25)

,item_id,dept_id,cat_id,store_id,state_id,wm_yr_wk,weekly_demand,date,sporting_event_days,national_event_days,...,lead_time_weeks,demand_mean_4w,demand_std_4w,demand_cv_4w,demand_mean_8w,demand_std_8w,demand_cv_8w,demand_mean_13w,demand_std_13w,demand_cv_13w
0,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11101,8,2011-01-29,0,0,...,0.472102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11102,9,2011-02-05,1,0,...,0.280002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11103,17,2011-02-12,0,0,...,0.535779,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11104,6,2011-02-19,0,1,...,0.562938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11105,18,2011-02-26,0,0,...,0.149852,10.00,4.830459,0.483046,NaN,NaN,NaN,NaN,NaN,NaN
5,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11106,19,2011-03-05,0,0,...,0.242546,12.50,5.916080,0.473286,NaN,NaN,NaN,NaN,NaN,NaN
6,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11107,6,2011-03-12,0,0,...,0.446834,15.00,6.055301,0.403687,NaN,NaN,NaN,NaN,NaN,NaN
7,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11108,8,2011-03-19,0,0,...,0.383394,12.25,7.228416,0.590075,NaN,NaN,NaN,NaN,NaN,NaN
8,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11109,8,2011-03-26,0,0,...,0.426171,12.75,6.701990,0.525646,11.375,5.604526,0.492706,NaN,NaN,NaN
9,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11110,19,2011-04-02,0,0,...,0.306708,10.25,5.909033,0.576491,11.375,5.604526,0.492706,NaN,NaN,NaN
10,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11111,10,2011-04-09,0,0,...,0.554200,10.25,5.909033,0.576491,12.625,6.093029,0.482616,NaN,NaN,NaN
11,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11112,18,2011-04-16,0,0,...,0.539685,11.25,5.251984,0.466843,11.750,5.873670,0.499887,NaN,NaN,NaN
12,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11113,14,2011-04-23,0,0,...,0.438004,13.75,5.560276,0.404384,13.250,5.725881,0.432142,NaN,NaN,NaN
13,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11114,9,2011-04-30,0,0,...,0.589606,15.25,4.112988,0.269704,12.750,5.418223,0.424959,12.307692,5.250153,0.426575
14,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11115,22,2011-05-07,0,0,...,0.495358,12.75,4.112988,0.322587,11.500,4.898979,0.425998,12.384615,5.188745,0.418967
15,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11116,8,2011-05-14,0,0,...,0.305815,15.75,5.560276,0.353033,13.500,5.554921,0.411476,13.384615,5.708743,0.426515
16,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11117,33,2011-05-21,0,0,...,0.481250,13.25,6.396614,0.482763,13.500,5.554921,0.411476,12.692308,5.779051,0.455319
17,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11118,17,2011-05-28,1,1,...,0.291588,18.00,11.860298,0.658905,16.625,8.348439,0.502162,14.769231,7.704478,0.521657
18,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11119,7,2011-06-04,0,0,...,0.554064,20.00,10.424331,0.521217,16.375,8.296944,0.506684,14.692308,7.674466,0.522346
19,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11120,14,2011-06-11,1,0,...,0.421439,16.25,12.038134,0.740808,16.000,8.684962,0.542810,13.769231,7.833197,0.568891
20,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11121,3,2011-06-18,0,0,...,0.402163,17.75,10.996211,0.619505,15.500,8.668498,0.559258,14.384615,7.478173,0.519873
21,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11122,16,2011-06-25,0,0,...,0.331296,10.25,6.396614,0.624060,14.125,9.745878,0.689974,14.000000,7.947746,0.567696
22,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11123,12,2011-07-02,0,1,...,0.603220,10.00,6.055301,0.605530,15.000,9.531901,0.635460,14.615385,7.751757,0.530383
23,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11124,6,2011-07-09,0,0,...,0.406496,11.25,5.737305,0.509983,13.750,9.130013,0.664001,14.076923,7.664437,0.544468
24,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11125,2,2011-07-16,0,0,...,0.367382,9.25,5.852350,0.632686,13.500,9.335034,0.691484,13.769231,7.917847,0.575039

#### Rolling Statistics for "Lead Time" ####

In [113]:
# Feature Engineering. Generating Rolling lead time stats for 4/8/13 weeks.

for w in [4, 8, 13]:
    df_weekly[f'lt_mean_{w}w'] = df_weekly.groupby(
        ['item_id', 'store_id'])['lead_time_weeks'].transform(
        lambda x: x.shift(1).rolling(w, min_periods=w).mean())
    
    df_weekly[f'lt_std_{w}w'] = df_weekly.groupby(
        ['item_id', 'store_id'])['lead_time_weeks'].transform(
        lambda x: x.shift(1).rolling(w, min_periods=w).std())
    
    df_weekly[f'lt_cv_{w}w'] = (
        df_weekly[f'lt_std_{w}w'] / 
        (df_weekly[f'lt_mean_{w}w'] + 1e-9)
    )

In [63]:
df_weekly.head(20)

,item_id,dept_id,cat_id,store_id,state_id,wm_yr_wk,weekly_demand,date,sporting_event_days,national_event_days,...,demand_cv_13w,lt_mean_4w,lt_std_4w,lt_cv_4w,lt_mean_8w,lt_std_8w,lt_cv_8w,lt_mean_13w,lt_std_13w,lt_cv_13w
0,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11101,8,2011-01-29,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11102,9,2011-02-05,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11103,17,2011-02-12,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11104,6,2011-02-19,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11105,18,2011-02-26,0,0,...,NaN,0.462705,0.127613,0.275797,NaN,NaN,NaN,NaN,NaN,NaN
5,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11106,19,2011-03-05,0,0,...,NaN,0.382143,0.200568,0.524851,NaN,NaN,NaN,NaN,NaN,NaN
6,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11107,6,2011-03-12,0,0,...,NaN,0.372779,0.207675,0.557099,NaN,NaN,NaN,NaN,NaN,NaN
7,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11108,8,2011-03-19,0,0,...,NaN,0.350543,0.188259,0.537049,NaN,NaN,NaN,NaN,NaN,NaN
8,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11109,8,2011-03-26,0,0,...,NaN,0.305657,0.134452,0.439880,0.384181,0.147559,0.384088,NaN,NaN,NaN
9,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11110,19,2011-04-02,0,0,...,NaN,0.374736,0.092002,0.245511,0.378440,0.144512,0.381862,NaN,NaN,NaN
10,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11111,10,2011-04-09,0,0,...,NaN,0.390777,0.061960,0.158557,0.381778,0.142203,0.372475,NaN,NaN,NaN
11,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11112,18,2011-04-16,0,0,...,NaN,0.417618,0.103602,0.248078,0.384080,0.145171,0.377970,NaN,NaN,NaN
12,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11113,14,2011-04-23,0,0,...,NaN,0.456691,0.115213,0.252278,0.381174,0.141258,0.370588,NaN,NaN,NaN
13,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11114,9,2011-04-30,0,0,...,0.426575,0.459649,0.114317,0.248704,0.417193,0.106247,0.254670,0.410632,0.131362,0.319901
14,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11115,22,2011-05-07,0,0,...,0.418967,0.530374,0.065051,0.122651,0.460575,0.095009,0.206283,0.419671,0.139720,0.332929
15,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11116,8,2011-05-14,0,0,...,0.426515,0.515663,0.064518,0.125117,0.466641,0.095554,0.204769,0.436237,0.134448,0.308200
16,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11117,33,2011-05-21,0,0,...,0.455319,0.457196,0.118706,0.259639,0.456943,0.108296,0.237001,0.418547,0.135385,0.323464
17,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11118,17,2011-05-28,1,1,...,0.521657,0.468007,0.118344,0.252868,0.463828,0.107810,0.232435,0.412263,0.129910,0.315113
18,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11119,7,2011-06-04,0,0,...,0.522346,0.393503,0.109772,0.278962,0.461938,0.111042,0.240382,0.423166,0.110557,0.261263
19,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11120,14,2011-06-11,1,0,...,0.568891,0.408180,0.129992,0.318467,0.461921,0.111026,0.240356,0.447129,0.101539,0.227090

In [114]:
# creating lag features. Demand of prev and a week before that. 

df_weekly['demand_lag1'] = df_weekly.groupby(
    ['item_id', 'store_id'])['weekly_demand'].transform(
    lambda x: x.shift(1))

df_weekly['demand_lag2'] = df_weekly.groupby(
    ['item_id', 'store_id'])['weekly_demand'].transform(
    lambda x: x.shift(2))

#### Calender features ####

In [115]:
df_weekly['week_of_year']      = df_weekly['date'].dt.isocalendar().week.astype(int)
df_weekly['month']             = df_weekly['date'].dt.month
df_weekly['quarter']           = df_weekly['date'].dt.quarter

In [116]:
df_weekly.columns

Index(['item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'wm_yr_wk',
       'weekly_demand', 'date', 'sporting_event_days', 'national_event_days',
       'religious_event_days', 'cultural_event_days', 'weekly_event_count',
       'sell_price', 'lead_time_days', 'lead_time_weeks', 'demand_mean_4w',
       'demand_std_4w', 'demand_cv_4w', 'demand_mean_8w', 'demand_std_8w',
       'demand_cv_8w', 'demand_mean_13w', 'demand_std_13w', 'demand_cv_13w',
       'lt_mean_4w', 'lt_std_4w', 'lt_cv_4w', 'lt_mean_8w', 'lt_std_8w',
       'lt_cv_8w', 'lt_mean_13w', 'lt_std_13w', 'lt_cv_13w', 'week_of_year',
       'month', 'quarter', 'cat_id_enc', 'dept_id_enc', 'store_id_enc',
       'state_id_enc', 'target_demand_std', 'target_lt_std', 'demand_lag1',
       'demand_lag2'],
      dtype='object')

In [75]:
df_weekly.head(30)

,item_id,dept_id,cat_id,store_id,state_id,wm_yr_wk,weekly_demand,date,sporting_event_days,national_event_days,...,lt_cv_4w,lt_mean_8w,lt_std_8w,lt_cv_8w,lt_mean_13w,lt_std_13w,lt_cv_13w,week_of_year,month,quarter
0,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11101,8,2011-01-29,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,1,1
1,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11102,9,2011-02-05,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,2,1
2,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11103,17,2011-02-12,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,2,1
3,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11104,6,2011-02-19,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,2,1
4,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11105,18,2011-02-26,0,0,...,0.275797,NaN,NaN,NaN,NaN,NaN,NaN,8,2,1
5,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11106,19,2011-03-05,0,0,...,0.524851,NaN,NaN,NaN,NaN,NaN,NaN,9,3,1
6,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11107,6,2011-03-12,0,0,...,0.557099,NaN,NaN,NaN,NaN,NaN,NaN,10,3,1
7,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11108,8,2011-03-19,0,0,...,0.537049,NaN,NaN,NaN,NaN,NaN,NaN,11,3,1
8,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11109,8,2011-03-26,0,0,...,0.439880,0.384181,0.147559,0.384088,NaN,NaN,NaN,12,3,1
9,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11110,19,2011-04-02,0,0,...,0.245511,0.378440,0.144512,0.381862,NaN,NaN,NaN,13,4,2
10,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11111,10,2011-04-09,0,0,...,0.158557,0.381778,0.142203,0.372475,NaN,NaN,NaN,14,4,2
11,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11112,18,2011-04-16,0,0,...,0.248078,0.384080,0.145171,0.377970,NaN,NaN,NaN,15,4,2
12,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11113,14,2011-04-23,0,0,...,0.252278,0.381174,0.141258,0.370588,NaN,NaN,NaN,16,4,2
13,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11114,9,2011-04-30,0,0,...,0.248704,0.417193,0.106247,0.254670,0.410632,0.131362,0.319901,17,4,2
14,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11115,22,2011-05-07,0,0,...,0.122651,0.460575,0.095009,0.206283,0.419671,0.139720,0.332929,18,5,2
15,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11116,8,2011-05-14,0,0,...,0.125117,0.466641,0.095554,0.204769,0.436237,0.134448,0.308200,19,5,2
16,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11117,33,2011-05-21,0,0,...,0.259639,0.456943,0.108296,0.237001,0.418547,0.135385,0.323464,20,5,2
17,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11118,17,2011-05-28,1,1,...,0.252868,0.463828,0.107810,0.232435,0.412263,0.129910,0.315113,21,5,2
18,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11119,7,2011-06-04,0,0,...,0.278962,0.461938,0.111042,0.240382,0.423166,0.110557,0.261263,22,6,2
19,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11120,14,2011-06-11,1,0,...,0.318467,0.461921,0.111026,0.240356,0.447129,0.101539,0.227090,23,6,2
20,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11121,3,2011-06-18,0,0,...,0.254250,0.447141,0.106992,0.239280,0.445176,0.101789,0.228649,24,6,2
21,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11122,16,2011-06-25,0,0,...,0.257917,0.442661,0.108173,0.244370,0.446619,0.100969,0.226074,25,6,2
22,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11123,12,2011-07-02,0,1,...,0.217698,0.410372,0.095901,0.233692,0.439321,0.105880,0.241008,26,7,3
23,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11124,6,2011-07-09,0,0,...,0.263476,0.423854,0.115197,0.271784,0.462130,0.106864,0.231243,27,7,3
24,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11125,2,2011-07-16,0,0,...,0.268063,0.436440,0.105555,0.241855,0.450768,0.104075,0.230884,28,7,3
25,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11126,19,2011-07-23,0,0,...,0.284159,0.422206,0.106324,0.251829,0.437514,0.102771,0.234899,29,7,3
26,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11127,20,2011-07-30,0,0,...,0.252526,0.433041,0.094916,0.219186,0.432919,0.104075,0.240403,30,7,3
27,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11128,0,2011-08-06,0,0,...,0.150889,0.426860,0.087206,0.204297,0.426381,0.095748,0.224561,31,8,3
28,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11129,0,2011-08-13,0,0,...,0.161823,0.434277,0.089180,0.205354,0.425259,0.094955,0.223288,32,8,3
29,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11130,0,2011-08-20,0,0,...,0.123683,0.444948,0.089894,0.202031,0.439238,0.089101,0.202855,33,8,3

### Encoding categorical variables ###

In [117]:
from sklearn.preprocessing import LabelEncoder

for col in ['cat_id', 'dept_id', 'store_id', 'state_id']:
    le = LabelEncoder()
    df_weekly[f'{col}_enc'] = le.fit_transform(df_weekly[col])

In [85]:
df_weekly.sample(15)

,item_id,dept_id,cat_id,store_id,state_id,wm_yr_wk,weekly_demand,date,sporting_event_days,national_event_days,...,lt_mean_13w,lt_std_13w,lt_cv_13w,week_of_year,month,quarter,cat_id_enc,dept_id_enc,store_id_enc,state_id_enc
244962,FOODS_2_078,FOODS_2,FOODS,WI_3,WI,11145,0,2011-12-03,0,0,...,0.420505,0.123546,0.293804,48,12,4,0,1,2,2
1926565,HOUSEHOLD_1_315,HOUSEHOLD_1,HOUSEHOLD,CA_3,CA,11126,0,2011-07-23,0,0,...,0.922528,0.362342,0.392771,29,7,3,2,5,0,0
1684982,HOUSEHOLD_1_019,HOUSEHOLD_1,HOUSEHOLD,TX_2,TX,11125,0,2011-07-16,0,0,...,1.049955,0.380779,0.362663,28,7,3,2,5,1,1
2134534,HOUSEHOLD_2_026,HOUSEHOLD_2,HOUSEHOLD,TX_2,TX,11151,0,2012-01-14,0,1,...,0.920108,0.381753,0.414901,2,1,1,2,6,1,1
582831,FOODS_3_086,FOODS_3,FOODS,WI_3,WI,11340,24,2013-10-26,0,0,...,0.410138,0.107627,0.262417,43,10,4,0,2,2,2
1072785,FOODS_3_674,FOODS_3,FOODS,CA_3,CA,11601,27,2016-01-30,0,0,...,0.478672,0.108216,0.226076,4,1,1,0,2,0,0
935989,FOODS_3_510,FOODS_3,FOODS,CA_3,CA,11533,1,2015-09-12,0,0,...,0.388850,0.119440,0.307161,37,9,3,0,2,0,0
299656,FOODS_2_145,FOODS_2,FOODS,CA_3,CA,11542,32,2015-11-14,0,0,...,0.451893,0.164359,0.363711,46,11,4,0,1,0,0
362506,FOODS_2_220,FOODS_2,FOODS,TX_2,TX,11612,3,2016-04-16,0,0,...,0.430699,0.147692,0.342913,15,4,2,0,1,1,1
2539587,HOUSEHOLD_2_513,HOUSEHOLD_2,HOUSEHOLD,CA_3,CA,11206,0,2012-03-03,0,0,...,0.875816,0.399060,0.455643,9,3,1,2,6,0,0
2268486,HOUSEHOLD_2_188,HOUSEHOLD_2,HOUSEHOLD,CA_3,CA,11107,0,2011-03-12,0,0,...,NaN,NaN,NaN,10,3,1,2,6,0,0
2033416,HOUSEHOLD_1_446,HOUSEHOLD_1,HOUSEHOLD,CA_3,CA,11321,6,2013-06-15,1,0,...,0.946884,0.278083,0.293683,24,6,2,2,5,0,0
1970069,HOUSEHOLD_1_368,HOUSEHOLD_1,HOUSEHOLD,CA_3,CA,11405,0,2014-03-01,0,0,...,1.039737,0.215277,0.207050,9,3,1,2,5,0,0
2357024,HOUSEHOLD_2_294,HOUSEHOLD_2,HOUSEHOLD,CA_3,CA,11337,13,2013-10-05,0,0,...,1.032960,0.459036,0.444389,40,10,4,2,6,0,0
2143016,HOUSEHOLD_2_036,HOUSEHOLD_2,HOUSEHOLD,TX_2,TX,11436,4,2014-10-04,0,0,...,0.894244,0.384548,0.430025,40,10,4,2,6,1,1

In [118]:
# Creating target variables

df_weekly['target_demand_std'] = df_weekly.groupby(
    ['item_id', 'store_id'])['weekly_demand'].transform(
    lambda x: x.shift(-4).rolling(4, min_periods=4).std())

df_weekly['target_lt_std'] = df_weekly.groupby(
    ['item_id', 'store_id'])['lead_time_weeks'].transform(
    lambda x: x.shift(-4).rolling(4, min_periods=4).std())

In [96]:
df_weekly.head(5)

,item_id,dept_id,cat_id,store_id,state_id,wm_yr_wk,weekly_demand,date,sporting_event_days,national_event_days,...,lt_cv_13w,week_of_year,month,quarter,cat_id_enc,dept_id_enc,store_id_enc,state_id_enc,target_demand_std,target_lt_std
0,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11101,8,2011-01-29,0,0,...,NaN,4,1,1,0,0,0,0,NaN,NaN
1,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11102,9,2011-02-05,1,0,...,NaN,5,2,1,0,0,0,0,NaN,NaN
2,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11103,17,2011-02-12,0,0,...,NaN,6,2,1,0,0,0,0,NaN,NaN
3,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11104,6,2011-02-19,0,1,...,NaN,7,2,1,0,0,0,0,6.701990,0.134452
4,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11105,18,2011-02-26,0,0,...,NaN,8,2,1,0,0,0,0,5.909033,0.092002

In [119]:
# Dropping NaNs

# reset_index() is used to create a new index for the new DF after dropping NaN rows instead of using the old index. (drop=True) prevents the pandas
    # from trying to save the old broken index as a separate index column, which is unecessary. 

df_model = df_weekly.dropna().reset_index(drop=True)
print(df_model.shape)
print(df_model.isnull().sum().sum())

(2387367, 45)
0

In [120]:
print(df_model.columns.tolist())

['item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'wm_yr_wk', 'weekly_demand', 'date', 'sporting_event_days', 'national_event_days', 'religious_event_days', 'cultural_event_days', 'weekly_event_count', 'sell_price', 'lead_time_days', 'lead_time_weeks', 'demand_mean_4w', 'demand_std_4w', 'demand_cv_4w', 'demand_mean_8w', 'demand_std_8w', 'demand_cv_8w', 'demand_mean_13w', 'demand_std_13w', 'demand_cv_13w', 'lt_mean_4w', 'lt_std_4w', 'lt_cv_4w', 'lt_mean_8w', 'lt_std_8w', 'lt_cv_8w', 'lt_mean_13w', 'lt_std_13w', 'lt_cv_13w', 'week_of_year', 'month', 'quarter', 'cat_id_enc', 'dept_id_enc', 'store_id_enc', 'state_id_enc', 'target_demand_std', 'target_lt_std', 'demand_lag1', 'demand_lag2']

In [121]:
df_model.head(5)

,item_id,dept_id,cat_id,store_id,state_id,wm_yr_wk,weekly_demand,date,sporting_event_days,national_event_days,...,month,quarter,cat_id_enc,dept_id_enc,store_id_enc,state_id_enc,target_demand_std,target_lt_std,demand_lag1,demand_lag2
0,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11114,9,2011-04-30,0,0,...,4,2,0,0,0,0,10.424331,0.109772,14.0,18.0
1,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11115,22,2011-05-07,0,0,...,5,2,0,0,0,0,12.038134,0.129992,9.0,14.0
2,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11116,8,2011-05-14,0,0,...,5,2,0,0,0,0,10.996211,0.111129,22.0,9.0
3,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11117,33,2011-05-21,0,0,...,5,2,0,0,0,0,6.396614,0.107632,8.0,22.0
4,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11118,17,2011-05-28,1,1,...,5,2,0,0,0,0,6.055301,0.093009,33.0,8.0

In [122]:
exclude_cols = [
    'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id',
    'wm_yr_wk', 'date',
    'weekly_demand', 'lead_time_days', 'lead_time_weeks',
    'target_demand_std', 'target_lt_std'
]

feature_cols = [c for c in df_model.columns if c not in exclude_cols]
print(feature_cols)
print(f"Total features: {len(feature_cols)}")

['sporting_event_days', 'national_event_days', 'religious_event_days', 'cultural_event_days', 'weekly_event_count', 'sell_price', 'demand_mean_4w', 'demand_std_4w', 'demand_cv_4w', 'demand_mean_8w', 'demand_std_8w', 'demand_cv_8w', 'demand_mean_13w', 'demand_std_13w', 'demand_cv_13w', 'lt_mean_4w', 'lt_std_4w', 'lt_cv_4w', 'lt_mean_8w', 'lt_std_8w', 'lt_cv_8w', 'lt_mean_13w', 'lt_std_13w', 'lt_cv_13w', 'week_of_year', 'month', 'quarter', 'cat_id_enc', 'dept_id_enc', 'store_id_enc', 'state_id_enc', 'demand_lag1', 'demand_lag2']
Total features: 33

In [123]:
df_model[feature_cols]

,sporting_event_days,national_event_days,religious_event_days,cultural_event_days,weekly_event_count,sell_price,demand_mean_4w,demand_std_4w,demand_cv_4w,demand_mean_8w,...,lt_cv_13w,week_of_year,month,quarter,cat_id_enc,dept_id_enc,store_id_enc,state_id_enc,demand_lag1,demand_lag2
0,0,0,0,1,1,2.00,15.25,4.112988,0.269704,12.750,...,0.319901,17,4,2,0,0,0,0,14.0,18.0
1,0,0,0,1,1,2.00,12.75,4.112988,0.322587,11.500,...,0.332929,18,5,2,0,0,0,0,9.0,14.0
2,0,0,0,0,0,2.00,15.75,5.560276,0.353033,13.500,...,0.308200,19,5,2,0,0,0,0,22.0,9.0
3,0,0,0,0,0,2.00,13.25,6.396614,0.482763,13.500,...,0.323464,20,5,2,0,0,0,0,8.0,22.0
4,1,1,0,0,2,2.00,18.00,11.860298,0.658905,16.625,...,0.315113,21,5,2,0,0,0,0,33.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2387362,0,0,0,1,1,5.94,0.75,0.500000,0.666667,0.500,...,0.228039,12,3,1,2,6,2,2,0.0,1.0
2387363,0,0,0,0,0,5.94,0.50,0.577350,1.154701,0.375,...,0.224758,13,4,2,2,6,2,2,0.0,0.0
2387364,0,0,0,0,0,5.94,0.25,0.500000,2.000000,0.375,...,0.291464,14,4,2,2,6,2,2,0.0,0.0
2387365,0,0,0,0,0,5.94,0.00,0.000000,0.000000,0.375,...,0.288824,15,4,2,2,6,2,2,0.0,0.0
2387366,0,0,0,0,0,5.94,0.00,0.000000,0.000000,0.375,...,0.291684,16,4,2,2,6,2,2,0.0,0.0

In [125]:
# Train/Test split

split_index = int(len(df_model) * 0.80)

train = df_model.iloc[:split_index]
test  = df_model.iloc[split_index:]

X_train = train[feature_cols]
y_train = train['target_demand_std']

X_test = test[feature_cols]
y_test = test['target_demand_std']

print(f"Train size: {len(train)}")
print(f"Test size:  {len(test)}")

Train size: 1909893
Test size:  477474

In [126]:
# Training the model

from sklearn.ensemble import RandomForestRegressor

model_demand = RandomForestRegressor(
    n_estimators=200,
    max_depth=8,
    min_samples_leaf=5,
    random_state=42,
    n_jobs=-1
)

model_demand.fit(X_train, y_train)
print("Training complete.")

Training complete.

In [127]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

y_pred = model_demand.predict(X_test)
y_pred = np.clip(y_pred, 0, None)

mae  = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2   = r2_score(y_test, y_pred)

print(f"MAE:  {mae:.4f}")
print(f"RMSE: {rmse:.4f}")
print(f"R²:   {r2:.4f}")

MAE:  0.9766
RMSE: 2.9320
R²:   0.4332

In [128]:
import joblib
joblib.dump(model_demand, 'model_demand_std.pkl')
print("Model saved.")

Model saved.