In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("sales_train_evaluation.csv")

In [4]:
df.head(5)

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1932,d_1933,d_1934,d_1935,d_1936,d_1937,d_1938,d_1939,d_1940,d_1941
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,4,0,0,0,0,3,3,0,1
1,HOBBIES_1_002_CA_1_evaluation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,1,2,1,1,0,0,0,0,0
2,HOBBIES_1_003_CA_1_evaluation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,0,2,0,0,0,2,3,0,1
3,HOBBIES_1_004_CA_1_evaluation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,1,0,4,0,1,3,0,2,6
4,HOBBIES_1_005_CA_1_evaluation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,0,0,2,1,0,0,2,1,0

In [5]:
df.shape

(30490, 1947)

In [6]:
# Time range d1 to d1941 = 1941 days

In [7]:
# Unique SKUs/store
df.groupby("store_id")["item_id"].nunique()

store_id
CA_1    3049
CA_2    3049
CA_3    3049
CA_4    3049
TX_1    3049
TX_2    3049
TX_3    3049
WI_1    3049
WI_2    3049
WI_3    3049
Name: item_id, dtype: int64

In [8]:
df.loc[:, "d_1":].isnull().sum().any()

np.False_

In [9]:
# The data is daily not weekly

In [10]:
cal = pd.read_csv("calendar.csv")

In [11]:
cal.head(5)

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,NaN,NaN,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,NaN,NaN,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,NaN,NaN,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,NaN,NaN,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,NaN,NaN,1,0,1

In [12]:
cal.shape

(1969, 14)

In [13]:
# Pivoting rows to columns using melt() to have demand of 1941 days in column wise.

id_cols = ["id", "item_id", "dept_id", "cat_id", "store_id", "state_id"]

df_long = df.melt(id_vars = id_cols, var_name = "d", value_name = "demand") 
df_long.shape

(59181090, 8)

In [14]:
df_long.head(5)

,id,item_id,dept_id,cat_id,store_id,state_id,d,demand
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
1,HOBBIES_1_002_CA_1_evaluation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
2,HOBBIES_1_003_CA_1_evaluation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
3,HOBBIES_1_004_CA_1_evaluation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
4,HOBBIES_1_005_CA_1_evaluation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0

In [15]:
df_merged = df_long.merge(cal[["d", "date", "wm_yr_wk", "event_name_1", "event_type_1", "event_name_2", "event_type_2"]], on = 'd', how = 'left')
df_merged.head(5)

,id,item_id,dept_id,cat_id,store_id,state_id,d,demand,date,wm_yr_wk,event_name_1,event_type_1,event_name_2,event_type_2
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,NaN,NaN,NaN,NaN
1,HOBBIES_1_002_CA_1_evaluation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,NaN,NaN,NaN,NaN
2,HOBBIES_1_003_CA_1_evaluation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,NaN,NaN,NaN,NaN
3,HOBBIES_1_004_CA_1_evaluation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,NaN,NaN,NaN,NaN
4,HOBBIES_1_005_CA_1_evaluation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,NaN,NaN,NaN,NaN

In [16]:
df_merged.shape

(59181090, 14)

In [17]:
sell_prices = pd.read_csv("sell_prices.csv")
sell_prices.head(5)

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26
3     CA_1  HOBBIES_1_001     11328        8.26
4     CA_1  HOBBIES_1_001     11329        8.26

In [18]:
sell_prices.shape

(6841121, 4)

In [19]:
sell_prices.isnull().sum()

store_id      0
item_id       0
wm_yr_wk      0
sell_price    0
dtype: int64

In [20]:
# Checking the total demand and zero-demand % per store
store_summary = df_merged.groupby(['state_id','store_id']).agg(
    total_demand    = ('demand', 'sum'),
    zero_demand_pct = ('demand', lambda x: (x == 0).mean() * 100)
).reset_index().sort_values(['state_id', 'total_demand'], ascending=[True, False])

print(store_summary)

  state_id store_id  total_demand  zero_demand_pct
2       CA     CA_3      11363540        59.399768
0       CA     CA_1       7832248        63.759049
1       CA     CA_2       5818395        68.810291
3       CA     CA_4       4182534        71.999519
5       TX     TX_2       7329642        66.314172
6       TX     TX_3       6205940        69.715073
4       TX     TX_1       5692823        70.714074
8       WI     WI_2       6697988        70.480047
9       WI     WI_3       6542557        70.031610
7       WI     WI_1       5261506        68.754056

In [21]:
# Creating a subset of df_merged with just the top stores from each state "stores_to_keep" for ML training.

stores_to_keep = ['CA_3', 'TX_2', 'WI_3']
df = df_merged[df_merged['store_id'].isin(stores_to_keep)].copy()

print(df.shape)
print(df['store_id'].value_counts())

(17754327, 14)
store_id
CA_3    5918109
TX_2    5918109
WI_3    5918109
Name: count, dtype: int64

In [22]:
# Converting 'date' col to datetime data type 

df['date'] = pd.to_datetime(df['date'])

In [23]:
df.head(5)

,id,item_id,dept_id,cat_id,store_id,state_id,d,demand,date,wm_yr_wk,event_name_1,event_type_1,event_name_2,event_type_2
6098,HOBBIES_1_001_CA_3_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_3,CA,d_1,0,2011-01-29,11101,NaN,NaN,NaN,NaN
6099,HOBBIES_1_002_CA_3_evaluation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_3,CA,d_1,0,2011-01-29,11101,NaN,NaN,NaN,NaN
6100,HOBBIES_1_003_CA_3_evaluation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_3,CA,d_1,0,2011-01-29,11101,NaN,NaN,NaN,NaN
6101,HOBBIES_1_004_CA_3_evaluation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_3,CA,d_1,0,2011-01-29,11101,NaN,NaN,NaN,NaN
6102,HOBBIES_1_005_CA_3_evaluation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_3,CA,d_1,0,2011-01-29,11101,NaN,NaN,NaN,NaN

In [34]:
df['has_sporting_event']  = ((df['event_type_1'] == 'Sporting')  | (df['event_type_2'] == 'Sporting')).astype(int)
df['has_national_event']  = ((df['event_type_1'] == 'National')  | (df['event_type_2'] == 'National')).astype(int)
df['has_religious_event'] = ((df['event_type_1'] == 'Religious') | (df['event_type_2'] == 'Religious')).astype(int)
df['has_cultural_event']  = ((df['event_type_1'] == 'Cultural')  | (df['event_type_2'] == 'Cultural')).astype(int)
df['event_count']         = (df['event_name_1'].notna().astype(int) + df['event_name_2'].notna().astype(int))

In [35]:
df_weekly = df.groupby(
    ['item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'wm_yr_wk'],
    as_index=False
).agg(
    weekly_demand        = ('demand', 'sum'),
    date                 = ('date', 'first'),
    sporting_event_days   = ('has_sporting_event', 'sum'),
    national_event_days  = ('has_national_event', 'sum'),
    religious_event_days  = ('has_religious_event','sum'),
    cultural_event_days   = ('has_cultural_event', 'sum'),
    weekly_event_count   = ('event_count', 'sum'),
)

df_weekly = df_weekly.sort_values(
    ['item_id', 'store_id', 'wm_yr_wk']
).reset_index(drop=True)

In [36]:
df_weekly.head(5)
print(df_weekly.shape)

(2542866, 13)

In [37]:
df_weekly = df_weekly.merge(
    sell_prices[['store_id', 'item_id', 'wm_yr_wk', 'sell_price']],
    on=['store_id', 'item_id', 'wm_yr_wk'],
    how='left'
)

In [38]:
# After merging with sell_prices data

df_weekly.head(5)

,item_id,dept_id,cat_id,store_id,state_id,wm_yr_wk,weekly_demand,date,sporting_event_days,national_event_days,religious_event_days,cultural_event_days,weekly_event_count,sell_price
0,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11101,8,2011-01-29,0,0,0,0,0,2.0
1,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11102,9,2011-02-05,1,0,0,0,1,2.0
2,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11103,17,2011-02-12,0,0,0,1,1,2.0
3,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11104,6,2011-02-19,0,1,0,0,1,2.0
4,FOODS_1_001,FOODS_1,FOODS,CA_3,CA,11105,18,2011-02-26,0,0,0,0,0,2.0

In [39]:
print(df_weekly.shape)
print(df_weekly['sell_price'].isnull().sum())

(2542866, 14)
488156

In [40]:
weeks_per_sku = df_weekly.groupby(['item_id', 'store_id'])['wm_yr_wk'].count()
print(weeks_per_sku.describe())

sample = df_weekly[
    (df_weekly['item_id'] == 'HOBBIES_1_001') &
    (df_weekly['store_id'] == 'CA_3')
]
print(f"Total weeks for this item-store: {len(sample)}")
#print(sample.head(10))

count    9147.0
mean      278.0
std         0.0
min       278.0
25%       278.0
50%       278.0
75%       278.0
max       278.0
Name: wm_yr_wk, dtype: float64
Total weeks for this item-store: 278

In [44]:
# Which categories have the most missing prices?
null_prices = df_weekly[df_weekly['sell_price'].isnull()]
print(null_prices.groupby('cat_id')['sell_price'].count())
print(null_prices.groupby('cat_id').size())

cat_id
FOODS        0
HOBBIES      0
HOUSEHOLD    0
Name: sell_price, dtype: int64
cat_id
FOODS        225805
HOBBIES       89895
HOUSEHOLD    172456
dtype: int64

In [45]:
# Are nulls concentrated at the start or end of the time period?
print(null_prices['wm_yr_wk'].describe())

count    488156.000000
mean      11208.525207
std          92.386608
min       11101.000000
25%       11127.000000
50%       11207.000000
75%       11250.000000
max       11602.000000
Name: wm_yr_wk, dtype: float64

In [46]:
# Sort first to ensure correct order before filling
df_weekly = df_weekly.sort_values(['item_id', 'store_id', 'wm_yr_wk'])

# Backfill first (fills early nulls with first known price)
# Then forward fill (handles any remaining mid-series gaps)
df_weekly['sell_price'] = df_weekly.groupby(
    ['item_id', 'store_id']
)['sell_price'].transform(lambda x: x.bfill().ffill())

# Verify nulls are gone
print(df_weekly['sell_price'].isnull().sum())

0